import React, { Component, PropTypes } from 'react';
import { ToastAndroid, StyleSheet, TouchableOpacity, View, Text, TextInput, Keyboard } from 'react-native';

import * as Progress from 'react-native-progress';

import TimerMixin from 'react-timer-mixin';


var PushNotification = require('react-native-push-notification');
PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    // onRegister: function(token) {
    //     console.log( 'TOKEN:', token );
    // },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },

    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications) 
    // senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    // permissions: {
    //     alert: true,
    //     badge: true,
    //     sound: true
    // },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
      * (optional) default: true
      * - Specified if permissions (ios) and token (android and ios) will requested or not,
      * - if not, you must call PushNotificationsHandler.requestPermissions() later
      */
    // requestPermissions: true,
});

export default class Dashboard extends Component {
  
  // the dashboard scene handles all the user interaction on before the timer kicks off
  mixins: [TimerMixin];
  constructor(props) {
    super(props);
    this.state = {
      meditationDuration: 0,
      counter:0,
      setIntervalID: null,
      buttonOpacity: 0.3,
      active: false,
      textInputValue:null,
      helpMessage:'(tap above to enter a custom amount)',
    };
  };

  componentDidMount() { // registers when keyboard is hidden and considers the action a "time setting"
    Keyboard.addListener('keyboardDidHide', (e) => {this._keyboardDidHide(e)});    
    console.log("meditationDuration "+this.state.meditationDuration);
        /*PushNotification.localNotification({
    
        /* Android Only Properties
        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: "My Notification Ticker", // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
        subText: "This is a subText", // (optional) default: none
        color: "red", // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification
         
        color: "blue", // (optional) default: system default
        // iOS and Android properties 
        title: "Congrats!", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
        message: "Meditation Session Complete", // (required)
        playSound: true, // (optional) default: true
        soundName: 'bell.wav', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    })*/
    PushNotification.localNotificationSchedule({
  message: "My Notification Message", // (required)
  date: new Date(Date.now() + (5 * 1000)), // in 60 secs
  playSound: true, // (optional) default: true
        soundName: 'bell.wav'
});
  }

  componentWillUnmount () {
    Keyboard.removeListener('keyboardDidHide', (e) => {this._keyboardDidHide(e)});
  }

  _keyboardDidHide(e){
    this.handleTimerButtonPress(this.state.textInputValue);
  }

  handleTimerButtonPress(time){

    this.setState({ meditationDuration: 0 }); // always resets meditationDuration for button press, submitting, or keyboardHide
    if (time !== null){
      let milisecs = time * 60 * 1000;
      console.log(time);
      if (Number.isInteger(milisecs) && time.length!==0 && time>=0 ) { //&& time%1===0
        this.setState({
          meditationDuration: milisecs,
          buttonOpacity:0.8,
          active: true,
          textInputValue: time+'',
        });
      } else {
        this.setState({buttonOpacity:0.3});
        ToastAndroid.show('Please enter a whole number greater than zero.', ToastAndroid.LONG, ToastAndroid.CENTER);
      }
    }
  }

  handleStartButtonPress(){
    if (this.state.active && this.state.meditationDuration !== 0) {
      this.props.navigator.push({
        title:'meditationTimer',
        passedInTime:this.state.meditationDuration
      })
    } else {
     ToastAndroid.show('Please enter a whole number greater than zero.', ToastAndroid.LONG, ToastAndroid.CENTER); 
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.textInputContainer}>
          <TextInput
            style={[styles.textInput, this.state.active ? styles.hugeText : styles.normalText]}
            multiline={true}
            placeholder={'How long is this session?'}
            value={this.state.textInputValue}
            onChangeText={(text)=> {
              this.setState({
                textInputValue:text,
                active:true,
              });
              if (text.length === 0){
                this.setState({
                  active:false,
                  buttonOpacity:0.3,
                });
              }
            }}
            onSubmitEditing={this.handleTimerButtonPress.bind(this, this.state.textInputValue)}
            keyboardType={'numeric'}
            blurOnSubmit={true}
          />
            {/* <Text>{this.state.textInputValue}</Text> 
          </TextInput>*/}
        </View>
      <Text style={styles.helpMessage}>{this.state.helpMessage}</Text>
        <View style={styles.buttonContainer}>
          <TouchableOpacity onPress={this.handleTimerButtonPress.bind(this, 10)}>
            <View style={[styles.circleButton,{backgroundColor:'#FF5722'}]}>
              <Text style={styles.buttonText}>10</Text>
            </View>
          </TouchableOpacity>          
          <TouchableOpacity onPress={this.handleTimerButtonPress.bind(this, 30)}>
            <View style={[styles.circleButton,{backgroundColor:'#FF5722'}]}>
              <Text style={styles.buttonText}>30</Text>
            </View>
          </TouchableOpacity>
          <TouchableOpacity onPress={this.handleTimerButtonPress.bind(this, 60)}>
            <View style={[styles.circleButton,{backgroundColor:'#FF5722'}]}>
              <Text style={styles.buttonText}>60</Text>
            </View>
          </TouchableOpacity>
        </View>

        {/* Submit button */}
        <TouchableOpacity
          onPress={this.handleStartButtonPress.bind(this)}
        >
          <View style={[styles.circleButton, {backgroundColor:'#8BC34A',opacity: this.state.buttonOpacity}]}>
            <Text style={styles.buttonText}>Start</Text>
          </View>
        </TouchableOpacity>
      </View>
    )
  }

  // static propTypes = {
  //   title: PropTypes.string.isRequired,
  //   routeIndex: PropTypes.number.isRequired,
  //   onForward: PropTypes.func.isRequired,
  //   onBack: PropTypes.func.isRequired,
  // }
}



const styles = StyleSheet.create({
  container: {
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    // backgroundColor:'#E1F5FE',
  },
  textInputContainer: {
    flexDirection:'row',
  },
  textInput: {
    flex:1,
    textAlign:'center',
    marginLeft:20,
    marginRight:20,
    fontSize:20,
    // marginTop:0,
    // marginBottom:0,
    // fontWeight:'100',
    // fontFamily:'Robot-thin',
  },
  helpMessage: {
    fontSize:10,
    opacity:.54
  },
  hugeText: {
    fontSize:90,
    opacity:.87,
  },
  normalText: {
    fontSize:25,
    fontWeight:'700',
    opacity:.87
  },
  buttonContainer: {
    flex:0,
    flexDirection: 'row',
    justifyContent:'center',
    alignItems:'center',
  },
  circleButton: {
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    width:85,
    height:85,
    borderRadius:50,
    margin:16
  },
  buttonText: {
    color:"white",
    fontSize:30,
  },
});

  // startCount(timerID){
  //  let setIntervalID = setInterval(() => {
  //     this.setState({ counter: this.state.counter+1 });
  //   }, 1000);
  //  this.setState({ setIntervalID: setIntervalID });
  // };

  // stopCount(timerID){
  //   if (timerID != null){
  //     clearInterval(timerID);
  //   }
  // };

  // resetCount(timerID){
  //   if (timerID != null){
  //     this.stopCount(timerID);
  //     this.setState({ counter: 0 });
  //   }
  // };
